services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fototeca
      POSTGRES_PASSWORD: fototeca
      POSTGRES_DB: fototeca
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
